[package]
name = "nightbot-voobly"
version = "1.4.0"
authors = ["Johannes Boczek <johannes.boczek@web.de>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
reqwest = "*"
serde_json = "*"
serde = "*"
serde_derive = "*"
url = "*"
cookie = "*"
